Parameters:
  AppName:
    Description: "Application Name"
    Type: String
    Default: serverless-php
  DBClusterName:
    Description: "Aurora RDS cluster name"
    Type: String
    Default: serverless-rds-cluster
  DatabaseName:
    Description: "Aurora RDS database name"
    Type: String
    Default: serverless_db
  DBMasterUserName:
    AllowedPattern: "[a-zA-Z0-9_]+"
    ConstraintDescription: must be between 1 to 16 alphanumeric characters.
    Description: The database admin account user name, between 1 to 16 alphanumeric characters.
    MaxLength: '16'
    MinLength: '1'
    Type: String
    Default: admin_user
  DBSubnetList:
    Description: "List of subnets for the Aurora RDS cluster"
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: "must be a list of at least three existing subnets associated with at least three different availability zones."
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: CloudFormation managed DB subnet group.
      SubnetIds:
        - !Select [0, !Ref DBSubnetList ]
        - !Select [1, !Ref DBSubnetList ]
        - !Select [2, !Ref DBSubnetList ]
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${self:provider.stage}-AuroraUserSecret"
      Description: RDS database auto-generated user password
      GenerateSecretString:
        SecretStringTemplate: !Join ['', ['{"username": "', !Ref DBMasterUserName, '"}' ]]
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      #Tags:
      #  -
      #    Key: AppName
      #    Value: !Ref AppName
  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Ref DBClusterName
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:password}}' ]]
      DatabaseName: !Ref DatabaseName
      Engine: aurora
      EngineMode: serverless
      EngineVersion: 5.6.10a
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 1
        SecondsUntilAutoPause: 900 # 15 min
      DBSubnetGroupName:
        Ref: DBSubnetGroup
Outputs:
  DatabaseName:
    Description: Aurora Database Name
    Value: !Ref DatabaseName
    Export:
      Name: !Sub ${self:service.name}-${self:provider.stage}-DatabaseName

  DatabaseSecretArn:
    Description: Aurora Secret ARN
    Value: !Ref DBSecret
    Export:
      Name: !Sub ${self:service.name}-${self:provider.stage}-DatabaseSecretArn

  DatabaseClusterID:
    Description: Aurora Cluster ID
    Value: !Ref RDSCluster
    Export:
      Name: !Sub ${self:service.name}-${self:provider.stage}-DatabaseClusterID

  AuroraDbURL:
    Description: Aurora Database URL
    Value: !GetAtt RDSCluster.Endpoint.Address
    Export:
      Name: !Sub ${self:service.name}-${self:provider.stage}-DatabaseURL

  DatabaseMasterUserName:
    Description: Aurora Database User
    Value: !Ref DBMasterUserName
    Export:
      Name: !Sub ${self:service.name}-${self:provider.stage}-DatabaseMasterUserName